# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
    commit-message:
      prefix: 'build(Dependabot pnpm):'
    # reviewers:
    #   - Add reviewers here
    pull-request-branch-name:
      separator: '-'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
    commit-message:
      prefix: 'build(Dependabot github-actions):'
    # reviewers:
    #   - Add reviewers here
    pull-request-branch-name:
      separator: '-'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
